= JetBrains IntelliJ IDEA Community
:uri-idea-home: https://www.jetbrains.com/idea/

{uri-idea-home}[IntelliJ IDEA Community^] is a fully-fledged commercial IDE for the JVM platform.

IntelliJ IDEA provides all the tools you need for productive enterprise, Web, and mobile development. The IDE supports
Java, Groovy, Kotlin, Scala, Android, JavaScript, SQL and lots of other languages and frameworks. It offers instant and
clever code completion, on-the-fly code analysis and reliable refactoring tools.

== Build, Install and Run Flatpak (locally)

Assuming `flatpak`, `flatpak-builder`, and `git` are installed, then execute the following commands:

[source,shell]
----
$ git clone https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community.git
$ cd com.jetbrains.IntelliJ-IDEA-Community/
$ flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak-builder build --force-clean --install-deps-from=flathub --install --user com.jetbrains.IntelliJ-IDEA-Community.yaml

# ...to uninstall the artifact
$ flatpak uninstall --delete-data --user com.jetbrains.IntelliJ-IDEA-Community

# ...and to clean-up everything
$ rm --force --recursive .flatpak-builder/ build/
$ flatpak uninstall --unused --user
$ flatpak remote-delete --user flathub
----

== Permissions

This application requests the following permissions:

* `device=all` because there are plugins that use the camera, people develop for certain controllers, etc.
* `filesystems=host` because you can have anything installed in your system and would like to be able to use it as before
* `sockets=ssh-auth` because (ideally) most developers use git using the Secure Shell Protocol

The rest are hopefully innocent or obvious enough to not require explanation!

// git submodule foreach git pull origin master
